import Footer from "../../components/Blog/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <body>{children}</body>
      <Footer />
    </div>
  );
}
